package com.example.hotel.mapper;

import com.example.hotel.entity.HotelInfo;
import com.example.hotel.entity.HotelInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface HotelInfoMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  long countByExample(HotelInfoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  int deleteByExample(HotelInfoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  int insert(HotelInfo row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  int insertSelective(HotelInfo row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  List<HotelInfo> selectByExample(HotelInfoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  HotelInfo selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  int updateByExampleSelective(@Param("row") HotelInfo row,
      @Param("example") HotelInfoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  int updateByExample(@Param("row") HotelInfo row, @Param("example") HotelInfoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  int updateByPrimaryKeySelective(HotelInfo row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * hotel_info
   *
   * @mbg.generated Mon Nov 04 21:06:18 GMT 2024
   */
  int updateByPrimaryKey(HotelInfo row);

  @Select("SELECT * FROM hotel_info WHERE hotel_name LIKE #{name} AND city LIKE #{city} AND address LIKE #{address} AND is_deleted = 0")
  List<HotelInfo> findHotels(@Param("name") String name, @Param("city") String city, @Param("address") String address);

  @Select("SELECT * FROM hotel_info WHERE id = #{id} AND is_deleted = 0")
  HotelInfo findHotelById(Long id);

  int updateHotel(HotelInfo hotelInfo);

  /**
   * Delete a hotel by its ID
   *
   * @param id Hotel ID
   * @return Number of rows affected
   */
  @Update("UPDATE hotel_info SET is_deleted = 1 WHERE id = #{id} AND is_deleted = 0")
  int deleteHotelById(Long id);
}