package com.example.hotel.mapper;

import com.example.hotel.entity.OrderDetail;
import com.example.hotel.entity.OrderDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  long countByExample(OrderDetailExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  int deleteByExample(OrderDetailExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  int insert(OrderDetail row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  int insertSelective(OrderDetail row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  List<OrderDetail> selectByExample(OrderDetailExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  OrderDetail selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  int updateByExampleSelective(@Param("row") OrderDetail row,
      @Param("example") OrderDetailExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  int updateByExample(@Param("row") OrderDetail row,
      @Param("example") OrderDetailExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  int updateByPrimaryKeySelective(OrderDetail row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_detail
   *
   * @mbg.generated Fri Nov 29 00:34:27 GMT 2024
   */
  int updateByPrimaryKey(OrderDetail row);
}