package com.example.hotel.mapper;

import com.example.hotel.entity.RoomInfo;
import com.example.hotel.entity.RoomInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomInfoMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  long countByExample(RoomInfoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  int deleteByExample(RoomInfoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  int insert(RoomInfo row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  int insertSelective(RoomInfo row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  List<RoomInfo> selectByExample(RoomInfoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  RoomInfo selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  int updateByExampleSelective(@Param("row") RoomInfo row,
      @Param("example") RoomInfoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  int updateByExample(@Param("row") RoomInfo row, @Param("example") RoomInfoExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  int updateByPrimaryKeySelective(RoomInfo row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * room_info
   *
   * @mbg.generated Fri Nov 29 01:46:56 GMT 2024
   */
  int updateByPrimaryKey(RoomInfo row);
}