package com.example.hotel.mapper;

import com.example.hotel.entity.UserPoints;
import com.example.hotel.entity.UserPointsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPointsMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  long countByExample(UserPointsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  int deleteByExample(UserPointsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  int deleteByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  int insert(UserPoints row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  int insertSelective(UserPoints row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  List<UserPoints> selectByExample(UserPointsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  UserPoints selectByPrimaryKey(Long id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  int updateByExampleSelective(@Param("row") UserPoints row,
      @Param("example") UserPointsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  int updateByExample(@Param("row") UserPoints row, @Param("example") UserPointsExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  int updateByPrimaryKeySelective(UserPoints row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * user_points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  int updateByPrimaryKey(UserPoints row);
}