server:
  port: 8080
  forward-headers-strategy: FRAMEWORK
  undertow:
    io-threads: 2
    worker-threads: 36
    buffer-size: 1024
    directBuffers: true
  servlet:
    session:
      timeout: 86400

spring:
  transaction:
    rollback-on-commit-failure: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySql配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1k160qpstc9hojzto.mysql.rds.aliyuncs.com:3306/hotel?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: Cs5721__
  thymeleaf:
    mode: HTML5
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
    check-template-location: false
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.hotel.entity
  configLocation: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.example.sens.entity
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 1
#    logic-not-delete-value: 0
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: true

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: error
        web: DEBUG
    com:
      fasterxml:
        jackson: DEBUG
  file:
    name: ./logs/log.log
#        web:
#          trace

application:
  formatted-version: 1.0.0

shiro:
  userNativeSessionManager: true

#mail:
#  smtp:
#    host: smtp.qq.com
#    username: 847064370@qq.com
#    password: vtvhcjsacnuubdaj
#  from:
#    name: Hotux

mail:
  host: smtp.exmail.qq.com
  from: 1483503963@qq.com
  user: 1483503963@qq.com
  pass: 89gr@@39
  port: 465
  sslEnable: true
  socketFactoryClass: javax.net.ssl.SSLSocketFactory
  socketFactoryFallback: true
  socketFactoryPort: 465
#swagger3 config
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  api-docs:
#    path: /v3/api-docs

#bank
aib:
  api-url: "https://api.aibms.com/payment"  # mock AIB API URL
  merchant-id: "12345678"  # mock AIB API merchant id
  api-key: "CS5721_AIB"  # mock AIB API Id
  secret-key: "Limerick"  # mock AIB API secret key
  currency: "EUR"
  payment-method: "CREDIT_CARD"

