package com.example.hotel.entity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

public class OrderBase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.id
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.hotel_id
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private Long hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.user_id
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.start_date
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private LocalDate startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.end_date
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private LocalDate endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.total_price
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.update_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.create_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.is_deleted
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.status
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.contact_name
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.contact_phone
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.estimated_arrival_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private LocalTime estimatedArrivalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.is_cancelled
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private Byte isCancelled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.operator
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.real_price
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private BigDecimal realPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.order_number
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_base.check_in_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    private LocalDateTime checkInTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.id
     *
     * @return the value of order_base.id
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.id
     *
     * @param id the value for order_base.id
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.hotel_id
     *
     * @return the value of order_base.hotel_id
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public Long getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.hotel_id
     *
     * @param hotelId the value for order_base.hotel_id
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.user_id
     *
     * @return the value of order_base.user_id
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.user_id
     *
     * @param userId the value for order_base.user_id
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.start_date
     *
     * @return the value of order_base.start_date
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.start_date
     *
     * @param startDate the value for order_base.start_date
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.end_date
     *
     * @return the value of order_base.end_date
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public LocalDate getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.end_date
     *
     * @param endDate the value for order_base.end_date
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.total_price
     *
     * @return the value of order_base.total_price
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.total_price
     *
     * @param totalPrice the value for order_base.total_price
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.update_time
     *
     * @return the value of order_base.update_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.update_time
     *
     * @param updateTime the value for order_base.update_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.create_time
     *
     * @return the value of order_base.create_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.create_time
     *
     * @param createTime the value for order_base.create_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.is_deleted
     *
     * @return the value of order_base.is_deleted
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.is_deleted
     *
     * @param isDeleted the value for order_base.is_deleted
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.status
     *
     * @return the value of order_base.status
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.status
     *
     * @param status the value for order_base.status
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.contact_name
     *
     * @return the value of order_base.contact_name
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.contact_name
     *
     * @param contactName the value for order_base.contact_name
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.contact_phone
     *
     * @return the value of order_base.contact_phone
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.contact_phone
     *
     * @param contactPhone the value for order_base.contact_phone
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.estimated_arrival_time
     *
     * @return the value of order_base.estimated_arrival_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public LocalTime getEstimatedArrivalTime() {
        return estimatedArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.estimated_arrival_time
     *
     * @param estimatedArrivalTime the value for order_base.estimated_arrival_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setEstimatedArrivalTime(LocalTime estimatedArrivalTime) {
        this.estimatedArrivalTime = estimatedArrivalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.is_cancelled
     *
     * @return the value of order_base.is_cancelled
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public Byte getIsCancelled() {
        return isCancelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.is_cancelled
     *
     * @param isCancelled the value for order_base.is_cancelled
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setIsCancelled(Byte isCancelled) {
        this.isCancelled = isCancelled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.operator
     *
     * @return the value of order_base.operator
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.operator
     *
     * @param operator the value for order_base.operator
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.real_price
     *
     * @return the value of order_base.real_price
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public BigDecimal getRealPrice() {
        return realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.real_price
     *
     * @param realPrice the value for order_base.real_price
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setRealPrice(BigDecimal realPrice) {
        this.realPrice = realPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.order_number
     *
     * @return the value of order_base.order_number
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.order_number
     *
     * @param orderNumber the value for order_base.order_number
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_base.check_in_time
     *
     * @return the value of order_base.check_in_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public LocalDateTime getCheckInTime() {
        return checkInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_base.check_in_time
     *
     * @param checkInTime the value for order_base.check_in_time
     *
     * @mbg.generated Mon Dec 09 09:54:09 GMT 2024
     */
    public void setCheckInTime(LocalDateTime checkInTime) {
        this.checkInTime = checkInTime;
    }
}