package com.example.hotel.entity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

public class OrderBaseExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public OrderBaseExample() {
    oredCriteria = new ArrayList<>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andHotelIdIsNull() {
      addCriterion("hotel_id is null");
      return (Criteria) this;
    }

    public Criteria andHotelIdIsNotNull() {
      addCriterion("hotel_id is not null");
      return (Criteria) this;
    }

    public Criteria andHotelIdEqualTo(Long value) {
      addCriterion("hotel_id =", value, "hotelId");
      return (Criteria) this;
    }

    public Criteria andHotelIdNotEqualTo(Long value) {
      addCriterion("hotel_id <>", value, "hotelId");
      return (Criteria) this;
    }

    public Criteria andHotelIdGreaterThan(Long value) {
      addCriterion("hotel_id >", value, "hotelId");
      return (Criteria) this;
    }

    public Criteria andHotelIdGreaterThanOrEqualTo(Long value) {
      addCriterion("hotel_id >=", value, "hotelId");
      return (Criteria) this;
    }

    public Criteria andHotelIdLessThan(Long value) {
      addCriterion("hotel_id <", value, "hotelId");
      return (Criteria) this;
    }

    public Criteria andHotelIdLessThanOrEqualTo(Long value) {
      addCriterion("hotel_id <=", value, "hotelId");
      return (Criteria) this;
    }

    public Criteria andHotelIdIn(List<Long> values) {
      addCriterion("hotel_id in", values, "hotelId");
      return (Criteria) this;
    }

    public Criteria andHotelIdNotIn(List<Long> values) {
      addCriterion("hotel_id not in", values, "hotelId");
      return (Criteria) this;
    }

    public Criteria andHotelIdBetween(Long value1, Long value2) {
      addCriterion("hotel_id between", value1, value2, "hotelId");
      return (Criteria) this;
    }

    public Criteria andHotelIdNotBetween(Long value1, Long value2) {
      addCriterion("hotel_id not between", value1, value2, "hotelId");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNull() {
      addCriterion("user_id is null");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNotNull() {
      addCriterion("user_id is not null");
      return (Criteria) this;
    }

    public Criteria andUserIdEqualTo(String value) {
      addCriterion("user_id =", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotEqualTo(String value) {
      addCriterion("user_id <>", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThan(String value) {
      addCriterion("user_id >", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThanOrEqualTo(String value) {
      addCriterion("user_id >=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThan(String value) {
      addCriterion("user_id <", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThanOrEqualTo(String value) {
      addCriterion("user_id <=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLike(String value) {
      addCriterion("user_id like", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotLike(String value) {
      addCriterion("user_id not like", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdIn(List<String> values) {
      addCriterion("user_id in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotIn(List<String> values) {
      addCriterion("user_id not in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdBetween(String value1, String value2) {
      addCriterion("user_id between", value1, value2, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotBetween(String value1, String value2) {
      addCriterion("user_id not between", value1, value2, "userId");
      return (Criteria) this;
    }

    public Criteria andStartDateIsNull() {
      addCriterion("start_date is null");
      return (Criteria) this;
    }

    public Criteria andStartDateIsNotNull() {
      addCriterion("start_date is not null");
      return (Criteria) this;
    }

    public Criteria andStartDateEqualTo(LocalDate value) {
      addCriterion("start_date =", value, "startDate");
      return (Criteria) this;
    }

    public Criteria andStartDateNotEqualTo(LocalDate value) {
      addCriterion("start_date <>", value, "startDate");
      return (Criteria) this;
    }

    public Criteria andStartDateGreaterThan(LocalDate value) {
      addCriterion("start_date >", value, "startDate");
      return (Criteria) this;
    }

    public Criteria andStartDateGreaterThanOrEqualTo(LocalDate value) {
      addCriterion("start_date >=", value, "startDate");
      return (Criteria) this;
    }

    public Criteria andStartDateLessThan(LocalDate value) {
      addCriterion("start_date <", value, "startDate");
      return (Criteria) this;
    }

    public Criteria andStartDateLessThanOrEqualTo(LocalDate value) {
      addCriterion("start_date <=", value, "startDate");
      return (Criteria) this;
    }

    public Criteria andStartDateIn(List<LocalDate> values) {
      addCriterion("start_date in", values, "startDate");
      return (Criteria) this;
    }

    public Criteria andStartDateNotIn(List<LocalDate> values) {
      addCriterion("start_date not in", values, "startDate");
      return (Criteria) this;
    }

    public Criteria andStartDateBetween(LocalDate value1, LocalDate value2) {
      addCriterion("start_date between", value1, value2, "startDate");
      return (Criteria) this;
    }

    public Criteria andStartDateNotBetween(LocalDate value1, LocalDate value2) {
      addCriterion("start_date not between", value1, value2, "startDate");
      return (Criteria) this;
    }

    public Criteria andEndDateIsNull() {
      addCriterion("end_date is null");
      return (Criteria) this;
    }

    public Criteria andEndDateIsNotNull() {
      addCriterion("end_date is not null");
      return (Criteria) this;
    }

    public Criteria andEndDateEqualTo(LocalDate value) {
      addCriterion("end_date =", value, "endDate");
      return (Criteria) this;
    }

    public Criteria andEndDateNotEqualTo(LocalDate value) {
      addCriterion("end_date <>", value, "endDate");
      return (Criteria) this;
    }

    public Criteria andEndDateGreaterThan(LocalDate value) {
      addCriterion("end_date >", value, "endDate");
      return (Criteria) this;
    }

    public Criteria andEndDateGreaterThanOrEqualTo(LocalDate value) {
      addCriterion("end_date >=", value, "endDate");
      return (Criteria) this;
    }

    public Criteria andEndDateLessThan(LocalDate value) {
      addCriterion("end_date <", value, "endDate");
      return (Criteria) this;
    }

    public Criteria andEndDateLessThanOrEqualTo(LocalDate value) {
      addCriterion("end_date <=", value, "endDate");
      return (Criteria) this;
    }

    public Criteria andEndDateIn(List<LocalDate> values) {
      addCriterion("end_date in", values, "endDate");
      return (Criteria) this;
    }

    public Criteria andEndDateNotIn(List<LocalDate> values) {
      addCriterion("end_date not in", values, "endDate");
      return (Criteria) this;
    }

    public Criteria andEndDateBetween(LocalDate value1, LocalDate value2) {
      addCriterion("end_date between", value1, value2, "endDate");
      return (Criteria) this;
    }

    public Criteria andEndDateNotBetween(LocalDate value1, LocalDate value2) {
      addCriterion("end_date not between", value1, value2, "endDate");
      return (Criteria) this;
    }

    public Criteria andTotalPriceIsNull() {
      addCriterion("total_price is null");
      return (Criteria) this;
    }

    public Criteria andTotalPriceIsNotNull() {
      addCriterion("total_price is not null");
      return (Criteria) this;
    }

    public Criteria andTotalPriceEqualTo(BigDecimal value) {
      addCriterion("total_price =", value, "totalPrice");
      return (Criteria) this;
    }

    public Criteria andTotalPriceNotEqualTo(BigDecimal value) {
      addCriterion("total_price <>", value, "totalPrice");
      return (Criteria) this;
    }

    public Criteria andTotalPriceGreaterThan(BigDecimal value) {
      addCriterion("total_price >", value, "totalPrice");
      return (Criteria) this;
    }

    public Criteria andTotalPriceGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("total_price >=", value, "totalPrice");
      return (Criteria) this;
    }

    public Criteria andTotalPriceLessThan(BigDecimal value) {
      addCriterion("total_price <", value, "totalPrice");
      return (Criteria) this;
    }

    public Criteria andTotalPriceLessThanOrEqualTo(BigDecimal value) {
      addCriterion("total_price <=", value, "totalPrice");
      return (Criteria) this;
    }

    public Criteria andTotalPriceIn(List<BigDecimal> values) {
      addCriterion("total_price in", values, "totalPrice");
      return (Criteria) this;
    }

    public Criteria andTotalPriceNotIn(List<BigDecimal> values) {
      addCriterion("total_price not in", values, "totalPrice");
      return (Criteria) this;
    }

    public Criteria andTotalPriceBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("total_price between", value1, value2, "totalPrice");
      return (Criteria) this;
    }

    public Criteria andTotalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("total_price not between", value1, value2, "totalPrice");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNull() {
      addCriterion("update_time is null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNotNull() {
      addCriterion("update_time is not null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
      addCriterion("update_time =", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
      addCriterion("update_time <>", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
      addCriterion("update_time >", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
      addCriterion("update_time >=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThan(LocalDateTime value) {
      addCriterion("update_time <", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
      addCriterion("update_time <=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
      addCriterion("update_time in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
      addCriterion("update_time not in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
      addCriterion("update_time between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
      addCriterion("update_time not between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNull() {
      addCriterion("create_time is null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNotNull() {
      addCriterion("create_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeEqualTo(LocalDateTime value) {
      addCriterion("create_time =", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
      addCriterion("create_time <>", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
      addCriterion("create_time >", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
      addCriterion("create_time >=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThan(LocalDateTime value) {
      addCriterion("create_time <", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
      addCriterion("create_time <=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIn(List<LocalDateTime> values) {
      addCriterion("create_time in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
      addCriterion("create_time not in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
      addCriterion("create_time between", value1, value2, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
      addCriterion("create_time not between", value1, value2, "createTime");
      return (Criteria) this;
    }

    public Criteria andIsDeletedIsNull() {
      addCriterion("is_deleted is null");
      return (Criteria) this;
    }

    public Criteria andIsDeletedIsNotNull() {
      addCriterion("is_deleted is not null");
      return (Criteria) this;
    }

    public Criteria andIsDeletedEqualTo(Byte value) {
      addCriterion("is_deleted =", value, "isDeleted");
      return (Criteria) this;
    }

    public Criteria andIsDeletedNotEqualTo(Byte value) {
      addCriterion("is_deleted <>", value, "isDeleted");
      return (Criteria) this;
    }

    public Criteria andIsDeletedGreaterThan(Byte value) {
      addCriterion("is_deleted >", value, "isDeleted");
      return (Criteria) this;
    }

    public Criteria andIsDeletedGreaterThanOrEqualTo(Byte value) {
      addCriterion("is_deleted >=", value, "isDeleted");
      return (Criteria) this;
    }

    public Criteria andIsDeletedLessThan(Byte value) {
      addCriterion("is_deleted <", value, "isDeleted");
      return (Criteria) this;
    }

    public Criteria andIsDeletedLessThanOrEqualTo(Byte value) {
      addCriterion("is_deleted <=", value, "isDeleted");
      return (Criteria) this;
    }

    public Criteria andIsDeletedIn(List<Byte> values) {
      addCriterion("is_deleted in", values, "isDeleted");
      return (Criteria) this;
    }

    public Criteria andIsDeletedNotIn(List<Byte> values) {
      addCriterion("is_deleted not in", values, "isDeleted");
      return (Criteria) this;
    }

    public Criteria andIsDeletedBetween(Byte value1, Byte value2) {
      addCriterion("is_deleted between", value1, value2, "isDeleted");
      return (Criteria) this;
    }

    public Criteria andIsDeletedNotBetween(Byte value1, Byte value2) {
      addCriterion("is_deleted not between", value1, value2, "isDeleted");
      return (Criteria) this;
    }

    public Criteria andStatusIsNull() {
      addCriterion("status is null");
      return (Criteria) this;
    }

    public Criteria andStatusIsNotNull() {
      addCriterion("status is not null");
      return (Criteria) this;
    }

    public Criteria andStatusEqualTo(Byte value) {
      addCriterion("status =", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotEqualTo(Byte value) {
      addCriterion("status <>", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusGreaterThan(Byte value) {
      addCriterion("status >", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
      addCriterion("status >=", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusLessThan(Byte value) {
      addCriterion("status <", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusLessThanOrEqualTo(Byte value) {
      addCriterion("status <=", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusIn(List<Byte> values) {
      addCriterion("status in", values, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotIn(List<Byte> values) {
      addCriterion("status not in", values, "status");
      return (Criteria) this;
    }

    public Criteria andStatusBetween(Byte value1, Byte value2) {
      addCriterion("status between", value1, value2, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotBetween(Byte value1, Byte value2) {
      addCriterion("status not between", value1, value2, "status");
      return (Criteria) this;
    }

    public Criteria andContactNameIsNull() {
      addCriterion("contact_name is null");
      return (Criteria) this;
    }

    public Criteria andContactNameIsNotNull() {
      addCriterion("contact_name is not null");
      return (Criteria) this;
    }

    public Criteria andContactNameEqualTo(String value) {
      addCriterion("contact_name =", value, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameNotEqualTo(String value) {
      addCriterion("contact_name <>", value, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameGreaterThan(String value) {
      addCriterion("contact_name >", value, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameGreaterThanOrEqualTo(String value) {
      addCriterion("contact_name >=", value, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameLessThan(String value) {
      addCriterion("contact_name <", value, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameLessThanOrEqualTo(String value) {
      addCriterion("contact_name <=", value, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameLike(String value) {
      addCriterion("contact_name like", value, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameNotLike(String value) {
      addCriterion("contact_name not like", value, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameIn(List<String> values) {
      addCriterion("contact_name in", values, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameNotIn(List<String> values) {
      addCriterion("contact_name not in", values, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameBetween(String value1, String value2) {
      addCriterion("contact_name between", value1, value2, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactNameNotBetween(String value1, String value2) {
      addCriterion("contact_name not between", value1, value2, "contactName");
      return (Criteria) this;
    }

    public Criteria andContactPhoneIsNull() {
      addCriterion("contact_phone is null");
      return (Criteria) this;
    }

    public Criteria andContactPhoneIsNotNull() {
      addCriterion("contact_phone is not null");
      return (Criteria) this;
    }

    public Criteria andContactPhoneEqualTo(String value) {
      addCriterion("contact_phone =", value, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneNotEqualTo(String value) {
      addCriterion("contact_phone <>", value, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneGreaterThan(String value) {
      addCriterion("contact_phone >", value, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneGreaterThanOrEqualTo(String value) {
      addCriterion("contact_phone >=", value, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneLessThan(String value) {
      addCriterion("contact_phone <", value, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneLessThanOrEqualTo(String value) {
      addCriterion("contact_phone <=", value, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneLike(String value) {
      addCriterion("contact_phone like", value, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneNotLike(String value) {
      addCriterion("contact_phone not like", value, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneIn(List<String> values) {
      addCriterion("contact_phone in", values, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneNotIn(List<String> values) {
      addCriterion("contact_phone not in", values, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneBetween(String value1, String value2) {
      addCriterion("contact_phone between", value1, value2, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andContactPhoneNotBetween(String value1, String value2) {
      addCriterion("contact_phone not between", value1, value2, "contactPhone");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeIsNull() {
      addCriterion("estimated_arrival_time is null");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeIsNotNull() {
      addCriterion("estimated_arrival_time is not null");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeEqualTo(LocalTime value) {
      addCriterion("estimated_arrival_time =", value, "estimatedArrivalTime");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeNotEqualTo(LocalTime value) {
      addCriterion("estimated_arrival_time <>", value, "estimatedArrivalTime");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeGreaterThan(LocalTime value) {
      addCriterion("estimated_arrival_time >", value, "estimatedArrivalTime");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeGreaterThanOrEqualTo(LocalTime value) {
      addCriterion("estimated_arrival_time >=", value, "estimatedArrivalTime");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeLessThan(LocalTime value) {
      addCriterion("estimated_arrival_time <", value, "estimatedArrivalTime");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeLessThanOrEqualTo(LocalTime value) {
      addCriterion("estimated_arrival_time <=", value, "estimatedArrivalTime");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeIn(List<LocalTime> values) {
      addCriterion("estimated_arrival_time in", values, "estimatedArrivalTime");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeNotIn(List<LocalTime> values) {
      addCriterion("estimated_arrival_time not in", values, "estimatedArrivalTime");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeBetween(LocalTime value1, LocalTime value2) {
      addCriterion("estimated_arrival_time between", value1, value2, "estimatedArrivalTime");
      return (Criteria) this;
    }

    public Criteria andEstimatedArrivalTimeNotBetween(LocalTime value1, LocalTime value2) {
      addCriterion("estimated_arrival_time not between", value1, value2, "estimatedArrivalTime");
      return (Criteria) this;
    }

    public Criteria andIsCancelledIsNull() {
      addCriterion("is_cancelled is null");
      return (Criteria) this;
    }

    public Criteria andIsCancelledIsNotNull() {
      addCriterion("is_cancelled is not null");
      return (Criteria) this;
    }

    public Criteria andIsCancelledEqualTo(Byte value) {
      addCriterion("is_cancelled =", value, "isCancelled");
      return (Criteria) this;
    }

    public Criteria andIsCancelledNotEqualTo(Byte value) {
      addCriterion("is_cancelled <>", value, "isCancelled");
      return (Criteria) this;
    }

    public Criteria andIsCancelledGreaterThan(Byte value) {
      addCriterion("is_cancelled >", value, "isCancelled");
      return (Criteria) this;
    }

    public Criteria andIsCancelledGreaterThanOrEqualTo(Byte value) {
      addCriterion("is_cancelled >=", value, "isCancelled");
      return (Criteria) this;
    }

    public Criteria andIsCancelledLessThan(Byte value) {
      addCriterion("is_cancelled <", value, "isCancelled");
      return (Criteria) this;
    }

    public Criteria andIsCancelledLessThanOrEqualTo(Byte value) {
      addCriterion("is_cancelled <=", value, "isCancelled");
      return (Criteria) this;
    }

    public Criteria andIsCancelledIn(List<Byte> values) {
      addCriterion("is_cancelled in", values, "isCancelled");
      return (Criteria) this;
    }

    public Criteria andIsCancelledNotIn(List<Byte> values) {
      addCriterion("is_cancelled not in", values, "isCancelled");
      return (Criteria) this;
    }

    public Criteria andIsCancelledBetween(Byte value1, Byte value2) {
      addCriterion("is_cancelled between", value1, value2, "isCancelled");
      return (Criteria) this;
    }

    public Criteria andIsCancelledNotBetween(Byte value1, Byte value2) {
      addCriterion("is_cancelled not between", value1, value2, "isCancelled");
      return (Criteria) this;
    }

    public Criteria andOperatorIsNull() {
      addCriterion("operator is null");
      return (Criteria) this;
    }

    public Criteria andOperatorIsNotNull() {
      addCriterion("operator is not null");
      return (Criteria) this;
    }

    public Criteria andOperatorEqualTo(String value) {
      addCriterion("operator =", value, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorNotEqualTo(String value) {
      addCriterion("operator <>", value, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorGreaterThan(String value) {
      addCriterion("operator >", value, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorGreaterThanOrEqualTo(String value) {
      addCriterion("operator >=", value, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorLessThan(String value) {
      addCriterion("operator <", value, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorLessThanOrEqualTo(String value) {
      addCriterion("operator <=", value, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorLike(String value) {
      addCriterion("operator like", value, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorNotLike(String value) {
      addCriterion("operator not like", value, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorIn(List<String> values) {
      addCriterion("operator in", values, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorNotIn(List<String> values) {
      addCriterion("operator not in", values, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorBetween(String value1, String value2) {
      addCriterion("operator between", value1, value2, "operator");
      return (Criteria) this;
    }

    public Criteria andOperatorNotBetween(String value1, String value2) {
      addCriterion("operator not between", value1, value2, "operator");
      return (Criteria) this;
    }

    public Criteria andRealPriceIsNull() {
      addCriterion("real_price is null");
      return (Criteria) this;
    }

    public Criteria andRealPriceIsNotNull() {
      addCriterion("real_price is not null");
      return (Criteria) this;
    }

    public Criteria andRealPriceEqualTo(BigDecimal value) {
      addCriterion("real_price =", value, "realPrice");
      return (Criteria) this;
    }

    public Criteria andRealPriceNotEqualTo(BigDecimal value) {
      addCriterion("real_price <>", value, "realPrice");
      return (Criteria) this;
    }

    public Criteria andRealPriceGreaterThan(BigDecimal value) {
      addCriterion("real_price >", value, "realPrice");
      return (Criteria) this;
    }

    public Criteria andRealPriceGreaterThanOrEqualTo(BigDecimal value) {
      addCriterion("real_price >=", value, "realPrice");
      return (Criteria) this;
    }

    public Criteria andRealPriceLessThan(BigDecimal value) {
      addCriterion("real_price <", value, "realPrice");
      return (Criteria) this;
    }

    public Criteria andRealPriceLessThanOrEqualTo(BigDecimal value) {
      addCriterion("real_price <=", value, "realPrice");
      return (Criteria) this;
    }

    public Criteria andRealPriceIn(List<BigDecimal> values) {
      addCriterion("real_price in", values, "realPrice");
      return (Criteria) this;
    }

    public Criteria andRealPriceNotIn(List<BigDecimal> values) {
      addCriterion("real_price not in", values, "realPrice");
      return (Criteria) this;
    }

    public Criteria andRealPriceBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("real_price between", value1, value2, "realPrice");
      return (Criteria) this;
    }

    public Criteria andRealPriceNotBetween(BigDecimal value1, BigDecimal value2) {
      addCriterion("real_price not between", value1, value2, "realPrice");
      return (Criteria) this;
    }

    public Criteria andOrderNumberIsNull() {
      addCriterion("order_number is null");
      return (Criteria) this;
    }

    public Criteria andOrderNumberIsNotNull() {
      addCriterion("order_number is not null");
      return (Criteria) this;
    }

    public Criteria andOrderNumberEqualTo(String value) {
      addCriterion("order_number =", value, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberNotEqualTo(String value) {
      addCriterion("order_number <>", value, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberGreaterThan(String value) {
      addCriterion("order_number >", value, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberGreaterThanOrEqualTo(String value) {
      addCriterion("order_number >=", value, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberLessThan(String value) {
      addCriterion("order_number <", value, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberLessThanOrEqualTo(String value) {
      addCriterion("order_number <=", value, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberLike(String value) {
      addCriterion("order_number like", value, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberNotLike(String value) {
      addCriterion("order_number not like", value, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberIn(List<String> values) {
      addCriterion("order_number in", values, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberNotIn(List<String> values) {
      addCriterion("order_number not in", values, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberBetween(String value1, String value2) {
      addCriterion("order_number between", value1, value2, "orderNumber");
      return (Criteria) this;
    }

    public Criteria andOrderNumberNotBetween(String value1, String value2) {
      addCriterion("order_number not between", value1, value2, "orderNumber");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * order_base
   *
   * @mbg.generated do_not_delete_during_merge Thu Nov 28 17:11:21 GMT 2024
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * order_base
   *
   * @mbg.generated Thu Nov 28 17:11:21 GMT 2024
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}