package com.example.hotel.entity;

import java.time.LocalDateTime;

public class PointInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_info.id
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_info.order_id
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_info.update_time
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_info.create_time
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_info.is_deleted
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_info.point_count
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    private Integer pointCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_info.user_id
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_info.reason_type
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    private Byte reasonType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_info.id
     *
     * @return the value of point_info.id
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_info.id
     *
     * @param id the value for point_info.id
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_info.order_id
     *
     * @return the value of point_info.order_id
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_info.order_id
     *
     * @param orderId the value for point_info.order_id
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_info.update_time
     *
     * @return the value of point_info.update_time
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_info.update_time
     *
     * @param updateTime the value for point_info.update_time
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_info.create_time
     *
     * @return the value of point_info.create_time
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_info.create_time
     *
     * @param createTime the value for point_info.create_time
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_info.is_deleted
     *
     * @return the value of point_info.is_deleted
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_info.is_deleted
     *
     * @param isDeleted the value for point_info.is_deleted
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_info.point_count
     *
     * @return the value of point_info.point_count
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public Integer getPointCount() {
        return pointCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_info.point_count
     *
     * @param pointCount the value for point_info.point_count
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public void setPointCount(Integer pointCount) {
        this.pointCount = pointCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_info.user_id
     *
     * @return the value of point_info.user_id
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_info.user_id
     *
     * @param userId the value for point_info.user_id
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_info.reason_type
     *
     * @return the value of point_info.reason_type
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public Byte getReasonType() {
        return reasonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_info.reason_type
     *
     * @param reasonType the value for point_info.reason_type
     *
     * @mbg.generated Sun Nov 10 00:55:30 GMT 2024
     */
    public void setReasonType(Byte reasonType) {
        this.reasonType = reasonType;
    }
}