package com.example.hotel.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class RefundInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_info.id
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_info.order_id
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_info.refund_amount
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    private BigDecimal refundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_info.refund_reason
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    private String refundReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_info.refund_status
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    private Byte refundStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_info.created_at
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    private LocalDateTime createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_info.updated_at
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    private LocalDateTime updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_info.id
     *
     * @return the value of refund_info.id
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_info.id
     *
     * @param id the value for refund_info.id
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_info.order_id
     *
     * @return the value of refund_info.order_id
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_info.order_id
     *
     * @param orderId the value for refund_info.order_id
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_info.refund_amount
     *
     * @return the value of refund_info.refund_amount
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_info.refund_amount
     *
     * @param refundAmount the value for refund_info.refund_amount
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public void setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_info.refund_reason
     *
     * @return the value of refund_info.refund_reason
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public String getRefundReason() {
        return refundReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_info.refund_reason
     *
     * @param refundReason the value for refund_info.refund_reason
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public void setRefundReason(String refundReason) {
        this.refundReason = refundReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_info.refund_status
     *
     * @return the value of refund_info.refund_status
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public Byte getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_info.refund_status
     *
     * @param refundStatus the value for refund_info.refund_status
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public void setRefundStatus(Byte refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_info.created_at
     *
     * @return the value of refund_info.created_at
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_info.created_at
     *
     * @param createdAt the value for refund_info.created_at
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_info.updated_at
     *
     * @return the value of refund_info.updated_at
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_info.updated_at
     *
     * @param updatedAt the value for refund_info.updated_at
     *
     * @mbg.generated Fri Dec 06 03:08:55 GMT 2024
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}