package com.example.hotel.entity;

import java.time.LocalDateTime;

public class RoomInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.id
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.hotel_id
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    private Long hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_type_id
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    private Long roomTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.update_time
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.create_time
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.is_deleted
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_number
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    private String roomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.room_key
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    private String roomKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.id
     *
     * @return the value of room_info.id
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */

    private Long priceRangeMin;
    private Long priceRangeMax;


    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.id
     *
     * @param id the value for room_info.id
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.hotel_id
     *
     * @return the value of room_info.hotel_id
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public Long getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.hotel_id
     *
     * @param hotelId the value for room_info.hotel_id
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public void setHotelId(Long hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.room_type_id
     *
     * @return the value of room_info.room_type_id
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public Long getRoomTypeId() {
        return roomTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.room_type_id
     *
     * @param roomTypeId the value for room_info.room_type_id
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public void setRoomTypeId(Long roomTypeId) {
        this.roomTypeId = roomTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.update_time
     *
     * @return the value of room_info.update_time
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.update_time
     *
     * @param updateTime the value for room_info.update_time
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.create_time
     *
     * @return the value of room_info.create_time
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.create_time
     *
     * @param createTime the value for room_info.create_time
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.is_deleted
     *
     * @return the value of room_info.is_deleted
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.is_deleted
     *
     * @param isDeleted the value for room_info.is_deleted
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.room_number
     *
     * @return the value of room_info.room_number
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.room_number
     *
     * @param roomNumber the value for room_info.room_number
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.room_key
     *
     * @return the value of room_info.room_key
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public String getRoomKey() {
        return roomKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.room_key
     *
     * @param roomKey the value for room_info.room_key
     *
     * @mbg.generated Sat Nov 09 15:54:04 GMT 2024
     */
    public void setRoomKey(String roomKey) {
        this.roomKey = roomKey;
    }

    public Long getPriceRangeMin() {
        return priceRangeMin;
    }

    public void setPriceRangeMin(Long priceRangeMin) {
        this.priceRangeMin = priceRangeMin;
    }

    public Long getPriceRangeMax() {
        return priceRangeMax;
    }

    public void setPriceRangeMax(Long priceRangeMax) {
        this.priceRangeMax = priceRangeMax;
    }

}