package com.example.hotel.entity;

import lombok.Data;

import javax.persistence.*;
import java.util.Date;

@Entity // Annotated as a JPA entity
@Table(name = "user") // Mapped to the table name in the database
public class User {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.id
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.user_id
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private String userId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.email
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private String email;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.phone
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private String phone;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.user_name
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private String userName;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.password
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private String password;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.user_type
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private Byte userType;

  private String approveStatus;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.member_ship
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private Byte memberShip;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.salt
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private String salt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.update_time
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private Date updateTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.create_time
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user.is_deleted
   *
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  private Byte isDeleted;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.id
   *
   * @return the value of user.id
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.id
   *
   * @param id the value for user.id
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.user_id
   *
   * @return the value of user.user_id
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public String getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.user_id
   *
   * @param userId the value for user.user_id
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.email
   *
   * @return the value of user.email
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public String getEmail() {
    return email;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.email
   *
   * @param email the value for user.email
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.phone
   *
   * @return the value of user.phone
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public String getPhone() {
    return phone;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.phone
   *
   * @param phone the value for user.phone
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.user_name
   *
   * @return the value of user.user_name
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public String getUserName() {
    return userName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.user_name
   *
   * @param userName the value for user.user_name
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.password
   *
   * @return the value of user.password
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.password
   *
   * @param password the value for user.password
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.user_type
   *
   * @return the value of user.user_type
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public Byte getUserType() {
    return userType;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.user_type
   *
   * @param userType the value for user.user_type
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setUserType(Byte userType) {
    this.userType = userType;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.member_ship
   *
   * @return the value of user.member_ship
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public Byte getMemberShip() {
    return memberShip;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.member_ship
   *
   * @param memberShip the value for user.member_ship
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setMemberShip(Byte memberShip) {
    this.memberShip = memberShip;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.salt
   *
   * @return the value of user.salt
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public String getSalt() {
    return salt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.salt
   *
   * @param salt the value for user.salt
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setSalt(String salt) {
    this.salt = salt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.update_time
   *
   * @return the value of user.update_time
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.update_time
   *
   * @param updateTime the value for user.update_time
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.create_time
   *
   * @return the value of user.create_time
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.create_time
   *
   * @param createTime the value for user.create_time
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user.is_deleted
   *
   * @return the value of user.is_deleted
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public Byte getIsDeleted() {
    return isDeleted;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user.is_deleted
   *
   * @param isDeleted the value for user.is_deleted
   * @mbg.generated Sat Nov 09 02:40:34 GMT 2024
   */
  public void setIsDeleted(Byte isDeleted) {
    this.isDeleted = isDeleted;
  }


}
