package com.example.hotel.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class UserPoints {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_points.id
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  private Long id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_points.user_id
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  private String userId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_points.points
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  private Integer points;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_points.order_id
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  private Long orderId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_points.is_deleted
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  private Byte isDeleted;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_points.update_time
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  private LocalDateTime updateTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_points.create_time
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  private LocalDateTime createTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * user_points.expense
   *
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  private BigDecimal expense;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_points.id
   *
   * @return the value of user_points.id
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_points.id
   *
   * @param id the value for user_points.id
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_points.user_id
   *
   * @return the value of user_points.user_id
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public String getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_points.user_id
   *
   * @param userId the value for user_points.user_id
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public void setUserId(String userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_points.points
   *
   * @return the value of user_points.points
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public Integer getPoints() {
    return points;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_points.points
   *
   * @param points the value for user_points.points
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public void setPoints(Integer points) {
    this.points = points;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_points.order_id
   *
   * @return the value of user_points.order_id
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public Long getOrderId() {
    return orderId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_points.order_id
   *
   * @param orderId the value for user_points.order_id
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public void setOrderId(Long orderId) {
    this.orderId = orderId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_points.is_deleted
   *
   * @return the value of user_points.is_deleted
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public Byte getIsDeleted() {
    return isDeleted;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_points.is_deleted
   *
   * @param isDeleted the value for user_points.is_deleted
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public void setIsDeleted(Byte isDeleted) {
    this.isDeleted = isDeleted;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_points.update_time
   *
   * @return the value of user_points.update_time
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public LocalDateTime getUpdateTime() {
    return updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_points.update_time
   *
   * @param updateTime the value for user_points.update_time
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public void setUpdateTime(LocalDateTime updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_points.create_time
   *
   * @return the value of user_points.create_time
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public LocalDateTime getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_points.create_time
   *
   * @param createTime the value for user_points.create_time
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public void setCreateTime(LocalDateTime createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column user_points.expense
   *
   * @return the value of user_points.expense
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public BigDecimal getExpense() {
    return expense;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column user_points.expense
   *
   * @param expense the value for user_points.expense
   * @mbg.generated Sat Nov 30 22:03:53 GMT 2024
   */
  public void setExpense(BigDecimal expense) {
    this.expense = expense;
  }
}